module ZOrder
  BACKGROUND, STARS, PLAYER, UI = *0..3
  SPACEWIDTH = 640
  SPACEHEIGHT = 480
  INITANGLE = 0.0
  TURNINCR = 4.5
  ACCELINCR = 0.5
  VELOCHANGE = 0.95
  ZPOSITION = 1
  STARSIZE = 25
  STARANDLIMIT = 4
  FONTSIZE = 20
  SCOREX = SCOREY = 10
  SCOREINCR = 10
  PROXIMITY = 35
end
